/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 assets/TEMPLE2.glb --transform 
Files: assets/TEMPLE2.glb [256.99MB] > C:\Users\baiik\Desktop\SAE402\TEMPLE2-transformed.glb [15.55MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/TEMPLE2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube009.geometry} material={materials.PaletteMaterial001} position={[-24.401, 13.468, 16.924]} rotation={[0, Math.PI / 4, 0.35]} scale={[1.29, 0.591, 0.239]} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.Porcelain} position={[10.761, 3.934, -7.762]} rotation={[0, Math.PI / 2, 0]} scale={[-1, 1, 1]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Porcelain} position={[36.395, -3.935, -29.317]} rotation={[Math.PI / 2, -0.459, -Math.PI / 2]} scale={[0.262, 0.12, 0.27]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Concrete} position={[0, -0.958, 0]} scale={[31.188, 7.156, 23.662]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Concrete.001']} position={[-35.678, 5.275, 28.195]} rotation={[0, 0.786, 0]} scale={[0.524, 0.299, 0.34]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Concrete} position={[0, 9.421, 0]} scale={[23.821, 3.866, 16.323]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.PaletteMaterial002} position={[-25.343, 2.882, 25.961]} rotation={[0, 0.2, 0]} scale={[1.682, 1.409, 1.682]} />
      <mesh geometry={nodes.Cube037.geometry} material={materials['Concrete.003']} position={[20.51, 32.316, -0.163]} scale={[-0.436, 0.506, 3.259]} />
      <mesh geometry={nodes.Cube013_1.geometry} material={materials['Porcelain.002']} position={[-20.954, 17.987, 16.82]} scale={[1.832, 0.243, 0.289]} />
      <mesh geometry={nodes.Cube013_3.geometry} material={materials['Porcelain.003']} position={[-20.954, 17.987, 16.82]} scale={[1.832, 0.243, 0.289]} />
    </group>
  )
}

useGLTF.preload('/TEMPLE2-transformed.glb')
